---
title: "Previous Research"
---

# Hyena behavior and ecology

As a research assistant with Dr. Kay Holekamp’s Mara Hyena Project (link) I participated in the study of Spotted Hyena (Crocuta crocuta) behavior and ecology. 

Behaviorally, hyenas are unique social predators that help us understand the evolution of different group behaviors and the ways in which these social structures change with different types of disturbance.

Ecologically, hyenas are survivors—able to adapt where many other large carnivores are not. These means that they can live alongside humans, altering their behavior in these spaces and many times coming into conflict with people. This makes them ideal ecological indicators for anthropogenic influences on population dynamics and behavior.

Because hyenas and people share spaces, this often creates tensions. I believe understanding ways to manage coexistence with these large predators can help us understand wildlife conflict mitigation in other areas as well.

To read more about current hyena research, visit the Hyena Project blog. To read more about my personal experiences with the project, visit my blog.



# Golden Gate Raptor Observatory

As a research intern at the GGRO, I assisted with the study of raptor migration biology.

Raptors are important predators in many ecosystems, yet they also often migrate long distances, creating a particular conservation challenge. The GGRO is a long-term citizen science research group that monitors populations of raptors.

Along with Dr. Chris Briggs and intern Kris Vanesky, we conducted a study of raptor health indicators. We examined blood parasites and white blood cell ratios in relation to migration timing and recovery rates.


# Tent roosting bat population limits

I conducted my first independent research project in college on the limitations of roost sites on tent roosting bat social group size. Working with Costa Rican collaborators at Tirimbina Biological Reserve and under the supervision of my local advisor Dr. Bernal Rodriguez-Herrera, I conducted an experimental trial to link ecological constraints of social populations. Tropical bats are important pollinators, insectivores, and frugivores; Bernal and his colleagues do outreach to explain the importance of these helpful animals to local school children. 
